# .air.toml

# ========== Build Settings ==========
[build]
cmd = "go build -o ./tmp/main.exe ."
bin = "./tmp/main.exe"
full_bin = ""
include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]
exclude_file = ["*_test.go"]
delay = 1000  # ms
stop_on_error = true
send_interrupt = true

# ========== Logging Settings ==========
[log]
time = true

# ========== Run Settings ==========
[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
