package main

import (
	"log"
	"pos/database"
	"pos/routes"

	"pos/validators"

	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
	"github.com/go-playground/validator/v10"

	_ "pos/docs" // docs is generated by Swag CLI, you have to import it.

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title POS (Point of Sale) API
// @version 1.0
// @description This is a comprehensive Point of Sale (POS) API server.

// @license.name MIT
// @license.url https://github.com/esaprakoso/pos-api/blob/main/LICENSE

// @host localhost:3000
// @BasePath /api
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	app := gin.Default()

	database.Connect()

	// register custom validators
	if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
		validators.RegisterCustomValidators(v, database.DB)
	}

	routes.SetupRoutes(app)

	// Swagger route
	app.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	log.Fatal(app.Run(":3000"))
}
